# `version` is now deprecated
# https://docs.docker.com/compose/compose-file/#version-top-level-element

services:
  next-ts-app:
    container_name: next-ts-app
    ports:
      - 1001:3000
    build:
      context: ./next-ts-app
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_DATABASE: ${POSTGRES_DATABASE}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    networks:
      - my_network
networks:
  my_network:
    external: true
